name: Deploy PROD API

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  deployments: write
  id-token: write

jobs:
  build_docker:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    strategy:
      fail-fast: false
      matrix:
        name: ['novu-lts/api']
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
      
      - name: Variables
        shell: bash
        run: |
          service=${{ matrix.name }}
          LATEST_VERSION=$(jq -r '.version' lerna.json)
          SERVICE_NAME=$(basename "${service//-/-}")
          SERVICE_COMMON_NAME=$(echo "$SERVICE_NAME" | sed 's/-ee$//')
          echo "LATEST_VERSION=$LATEST_VERSION" >> $GITHUB_ENV
          echo "SERVICE_NAME=$SERVICE_NAME" >> $GITHUB_ENV
          echo "SERVICE_COMMON_NAME=$SERVICE_COMMON_NAME" >> $GITHUB_ENV
          echo "REGISTRY_OWNER=musama619" >> $GITHUB_ENV
          echo "This is the service name: $SERVICE_NAME and release version: $LATEST_VERSION"

      - uses: ./.github/actions/setup-project
        with:
          submodules: ${{ contains (matrix.name,'-ee') }}

      # - name: Install pnpm
      #   uses: pnpm/action-setup@v3

      # - name: Use Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: 20.8.1
      #     cache: 'pnpm'

      # - name: Install dependencies
      #   run: pnpm install --frozen-lockfile

      - name: Setup Docker
        uses: crazy-max/ghaction-setup-docker@v2
        with:
          version: v24.0.6
          daemon-config: |
            {
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: build api
        run: pnpm build:api --skip-nx-cache
      
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      
      - name: Set Up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: 'image=moby/buildkit:v0.12.4'
      
      - uses: ./.github/actions/free-space
        name: Extend space in Action Container

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: musama619
          password: ${{ secrets.NOVU_TOKEN_FN }}

      - name: Build ${{ env.SERVICE_NAME }} Community Docker Image
        shell: bash
        env:
          DOCKER_BUILD_ARGUMENTS: >
            --cache-from type=registry,ref=ghcr.io/${{ env.REGISTRY_OWNER }}/cache:build-cache-${{ env.SERVICE_NAME }}-community
            --cache-to type=registry,ref=ghcr.io/${{ env.REGISTRY_OWNER }}/cache:build-cache-${{ env.SERVICE_NAME }}-community,mode=max
            --platform=linux/amd64,linux/arm64 --provenance=false
            --output=type=image,name=ghcr.io/${{ env.REGISTRY_OWNER }}/${{ env.SERVICE_NAME }},push-by-digest=true,name-canonical=true
        run: |
          cd apps/api
          pnpm run docker:build
          docker images

      - name: Find Built Docker Image
        run: docker images

      - name: Tag and Push Docker Image
        shell: bash
        run: |
          docker tag novu-api ghcr.io/musama619/${{ matrix.name }}:${{ env.LATEST_VERSION }}
          docker tag novu-api ghcr.io/musama619/${{ matrix.name }}:latest
          docker push ghcr.io/musama619/${{ matrix.name }}:${{ env.LATEST_VERSION }}
          docker push ghcr.io/musama619/${{ matrix.name }}:latest
